// ── Pixel Art SVG Character Sprites ──────────────
// 10x12 pixel grid per class, rendered as SVG
const CHAR_SPRITES = {
  novice: {
    p: {h:'#6B4226',H:'#8B5A3A',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',m:'#C4907A',t:'#A89070',T:'#8B7355',d:'#6B5839',b:'#5C4022',c:'#C8A848',l:'#7B6950',f:'#5A4030',F:'#4A3020',w:'#C49A30'},
    r: [
      '.....hhhhhh.....',
      '....hHhhhHhh....',
      '....hhhhhhhh....',
      '....hhsssshh....',
      '....sEessEes....',
      '.....sgssgs.....',
      '......smms......',
      '......gssg......',
      '.....tTTTTt.....',
      '....tTTTTTTt....',
      '...dTTTTTTTdw...',
      '...dTTTTTTTd.w..',
      '....dTTTTTd..w..',
      '.....bbccbb..w..',
      '.....llllll.w...',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
    ]
  },
  warrior: {
    p: {h:'#8B0000',H:'#B22222',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',a:'#DC143C',A:'#FF3040',d:'#8B0000',b:'#6B0000',c:'#FFD700',l:'#A01020',f:'#4A3728',F:'#3A2718',w:'#C0C0C0',W:'#A0A0A0'},
    r: [
      '.....hhhhhh.....',
      '....hHhhhHhh....',
      '....hhhhhhhh....',
      '....hhsssshh....',
      '....sEessEes....',
      '.....ssssss.....',
      '......gssg......',
      '.....aAAAAa.....',
      '....aAAAAAda....',
      '...dAAAAAAAdd...',
      '...dAAAdAAAdw...',
      '...dAAAAAAdd.w..',
      '....dAAAAdd..w..',
      '.....bbccbb.w...',
      '.....llllll.....',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
    ]
  },
  knight: {
    p: {c:'#A8A8A8',C:'#D0D0D0',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',a:'#4169E1',A:'#5A82FF',d:'#2B4D99',b:'#2B4D99',B:'#FFD700',l:'#3A3A50',f:'#333333',F:'#222222',w:'#C8C8C8',W:'#E8E8E8'},
    r: [
      '.....ccCCcc.....',
      '....cCCCCCCc....',
      '....cccccccc....',
      '....ccsssscc....',
      '....cEessEec....',
      '....cccccccc....',
      '.....cccccc.....',
      '....WaAAAAaW....',
      '..WWaAAAAAda....',
      '..WWaAAAAAda....',
      '..WWaAAdAAda....',
      '..WW.aAAAAa.....',
      '.....dAAAAd.....',
      '.....bBBBbb.....',
      '.....llllll.....',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
    ]
  },
  assassin: {
    p: {a:'#2D1B4E',A:'#3D2B6E',s:'#F5DEB3',E:'#C0A0FF',e:'#8B5CF6',d:'#1A1028',b:'#1A1028',B:'#8B5CF6',f:'#1A1028',F:'#0D0818',w:'#B0B0B0',W:'#D0D0D0'},
    r: [
      '......aaaa......',
      '.....aAAAAa.....',
      '....aAAAAAAa....',
      '....aAAAAAAa....',
      '....aEeAAeEa....',
      '....aAAAAAAa....',
      '.....aAAAAa.....',
      '......aaaa......',
      '.....dAAAAd.....',
      '....dAAAAAAd....',
      '..wddAAAAAAddw..',
      '...ddAAAAAAdd...',
      '....dAAAAAd.....',
      '.....bbBbb......',
      '.....dddddd.....',
      '.....dd..dd.....',
      '.....dd..dd.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
    ]
  },
  mage: {
    p: {a:'#1E3A5F',A:'#2A4F80',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',c:'#4488FF',C:'#66AAFF',d:'#142840',w:'#FFD700',W:'#DAA520',f:'#1E3A5F',F:'#142840'},
    r: [
      '.......cc.......',
      '......cccc......',
      '.....cccccc.....',
      '....ccAAAAcc....',
      '...CCCCCCCCCC...',
      '.....ssssss.....',
      '....sEessEes....',
      '.....ssssss.....',
      'w....aAAAAa.....',
      'w...aAAAAAda....',
      'w...aACCCAAd....',
      'w...aAAAAAda....',
      'W....aAAAAa.....',
      '....aaAAAAaa....',
      '...aaaaaaaaaa...',
      '...aaa....aaa...',
      '....ff....ff....',
      '................',
      '................',
      '................',
    ]
  },
  archer: {
    p: {a:'#2E8B57',A:'#3DA868',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',h:'#2E8B57',H:'#3DA868',d:'#1B5E20',b:'#1B5E20',B:'#3DA868',l:'#5A4838',f:'#4A3728',F:'#3A2718',w:'#8B4513',W:'#A0522D'},
    r: [
      '.....aaaaaa.....',
      '....aHAHAHaa....',
      '....aAAAAAAa....',
      '....ahssssha....',
      '....sEessEes....',
      '.....sgssgs.....',
      '......gssg......',
      '.....dAAAAd.....',
      '.w..dAAAAAda....',
      'W..dAAAAAAda....',
      'W..dAAAAAAda....',
      '.w..dAAAAAda....',
      '..w..dAAAAd.....',
      '.....bbBbb......',
      '.....llllll.....',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
    ]
  },
  priest: {
    p: {a:'#F0F0F0',A:'#FFFFFF',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',h:'#FFD700',H:'#FFE44D',c:'#FFD700',C:'#FFE44D',d:'#D0D0D0',w:'#DAA520',W:'#FFD700',f:'#DAA520',F:'#B8860B'},
    r: [
      '......cccc......',
      '.....cCCCCc.....',
      '....HhssssHh....',
      '....hhsssshh....',
      '....sEessEes....',
      '.....ssssss.....',
      '......gssg......',
      'w....aAAAAa.....',
      'w...aAAAAAAa....',
      'w...aAACCAAa....',
      'w...aACcCCAa....',
      'W...aAACCAAa....',
      '.....aAAAAa.....',
      '....aaAAAAaa....',
      '...aaaaaaaaaa...',
      '...aaa....aaa...',
      '....fF....Ff....',
      '................',
      '................',
      '................',
    ]
  },
  summoner: {
    p: {a:'#6A0DAD',A:'#8B2FC6',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',h:'#4B0082',H:'#6A0DAD',d:'#3D0066',c:'#9B59B6',C:'#BB79D6',w:'#C0A0FF',W:'#E0C0FF',f:'#4B0082',F:'#3D0066'},
    r: [
      '.....hhhhhh.....',
      '....hHhhhHhh....',
      '....hhhhhhhh....',
      '....hhsssshh....',
      '....sEessEes....',
      '.....ssssss.....',
      '......gssg......',
      '.c...aAAAAa...c.',
      '.C..aAAAAAda..C.',
      '....aACWWCAa....',
      '....aAAAAAda....',
      '.....aAAAAa.....',
      '....aaAAAAaa....',
      '...aaaaaaaaaa...',
      '...aaa....aaa...',
      '....ff....ff....',
      '................',
      '................',
      '................',
      '................',
    ]
  },
  shaman: {
    p: {a:'#556B2F',A:'#6B8B3A',s:'#D2B48C',g:'#B89A6E',E:'#FF4500',e:'#CC3700',c:'#D2691E',C:'#E8833A',d:'#3B4A1F',b:'#3B4A1F',w:'#8B4513',W:'#A0522D',f:'#4A3728',F:'#3A2718'},
    r: [
      '....cccccccc....',
      '...cCCCCCCCCc...',
      '...cCCCCCCCCc...',
      '...cCEeCCeECc...',
      '...cCCCCCCCCc...',
      '....cccccccc....',
      '......cccc......',
      '.....aAAAAa.....',
      'w...aAAAAAda....',
      'w..aAAAAAAda....',
      'w..aAAAAAAda....',
      'W...aAAAAAa.....',
      '.....aAAAAa.....',
      '.....bbCCbb.....',
      '.....dddddd.....',
      '.....dd..dd.....',
      '.....dd..dd.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
    ]
  },
  brawler: {
    p: {a:'#FF6600',A:'#FF8830',s:'#D2B48C',g:'#B89A6E',E:'#E8E0D0',e:'#3B2815',h:'#333333',H:'#444444',c:'#FF0000',C:'#FF3333',d:'#CC5500',b:'#CC5500',w:'#F0E68C',f:'#4A3728',F:'#3A2718',l:'#8B7355'},
    r: [
      '.....cccccc.....',
      '....chHhhHhc....',
      '....hhhhhhhh....',
      '....hhsssshh....',
      '....sEessEes....',
      '.....sgssgs.....',
      '......gssg......',
      '.....aAAAAa.....',
      '...saAAssAAas...',
      '..wsaAAAAAaasw..',
      '...saAAAAAas....',
      '....dAAAAAd.....',
      '.....bbbbbb.....',
      '.....llllll.....',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
      '................',
    ]
  },
  lancer: {
    p: {a:'#4682B4',A:'#5A96C8',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',h:'#333333',H:'#4A4A4A',d:'#36648B',b:'#36648B',c:'#C0C0C0',w:'#C0C0C0',W:'#E0E0E0',f:'#333333',F:'#222222',l:'#3A3A50'},
    r: [
      '..............Wc',
      '..............w.',
      '.....hhhhhh...w.',
      '....hHhhhHhh..w.',
      '....hhhhhhhh..w.',
      '....hhsssshh..w.',
      '....sEessEes..w.',
      '.....ssssss..w..',
      '.....aAAAAaw....',
      '....aAAAAAda....',
      '...dAAAdAAAdd...',
      '...dAAAAAAdd....',
      '....dAAAAdd.....',
      '.....bbbcbb.....',
      '.....llllll.....',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
    ]
  },
  sapper: {
    p: {a:'#8B6914',A:'#A58028',s:'#F5DEB3',g:'#D4B48E',E:'#E8E0D0',e:'#3B2815',c:'#FFD700',C:'#FFE44D',d:'#6B4914',b:'#6B4914',w:'#808080',W:'#A0A0A0',f:'#4A3728',F:'#3A2718',l:'#7B6950'},
    r: [
      '...cccccccc.....',
      '..cCCCCCCCCc....',
      '....ccsssscc....',
      '....sEessEes....',
      '.....sgssgs.....',
      '......gssg......',
      '.....aAAAAa.....',
      '....aAAAAAda....',
      '...dAAAAAAda.w..',
      '...dAAAAAAda..w.',
      '...dAAAAAda...w.',
      '....dAAAAd..w...',
      '.....bbcbb......',
      '.....llllll.....',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '....fFF..FFf....',
      '....fff..fff....',
      '................',
      '................',
    ]
  },
  summon_spirit: {
    p: {a:'#88CCFF',A:'#AADDFF',e:'#FFFFFF',d:'#6699CC'},
    r: [
      '......aaaa......',
      '.....aAAAAa.....',
      '....aAAAAAAa....',
      '....aA.ee.Aa....',
      '....aAAAAAAa....',
      '.....aAAAAa.....',
      '....aAAAAAAa....',
      '...aAAAAAAAAa...',
      '...aAAAAAAAAa...',
      '....aAAAAAAa....',
      '.....aAAAAa.....',
      '......aaaa......',
      '.......aa.......',
      '......aaaa......',
      '.....aa..aa.....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]
  },
  summon_golem: {
    p: {a:'#808080',A:'#A0A0A0',e:'#FF4500',b:'#606060',d:'#505050'},
    r: [
      '......aaaa......',
      '.....aAAAAa.....',
      '....aAAAAAAa....',
      '....aAeAAeAa....',
      '....aAAAAAAa....',
      '.....aaaaaa.....',
      '...aAAAAAAAAa...',
      '..aaAAAAAAAAaa..',
      '..aaAAAAAAAAaa..',
      '...aAAAAAAAAa...',
      '...aAAAAAAAAa...',
      '....aAAAAAAa....',
      '....bb....bb....',
      '....bb....bb....',
      '...bbb....bbb...',
      '...bbb....bbb...',
      '................',
      '................',
      '................',
      '................',
    ]
  },
};

function charSprite(cls, size) {
  const sp = CHAR_SPRITES[cls];
  if (!sp) return clsIcon(cls, size);
  const {p, r} = sp;
  const w = r[0].length, h = r.length;
  const svgH = Math.round(size * h / w);
  let out = '';
  for (let y = 0; y < h; y++) {
    const row = r[y];
    let x = 0;
    while (x < w) {
      const ch = row[x];
      if (ch === '.') { x++; continue; }
      let x2 = x + 1;
      while (x2 < w && row[x2] === ch) x2++;
      out += `<rect x="${x}" y="${y}" width="${x2-x}" height="1" fill="${p[ch]}"/>`;
      x = x2;
    }
  }
  return `<svg viewBox="0 0 ${w} ${h}" width="${size}" height="${svgH}" xmlns="http://www.w3.org/2000/svg" style="image-rendering:pixelated">${out}</svg>`;
}
